@startuml
'https://plantuml.com/class-diagram

package presentation {
    package ui {
        class ExerciseDetailScreen
        class ExerciseListScreen
    }
    package vm {
        class ExerciseViewModel
    }
}

package domain {
    class Exercise
}

package data {
    interface RemoteExerciseDataSource
    interface LocalExerciseDataSource
    interface ExerciseRepository
    class ExerciseRepositoryImpl
    class SqlDelightDataSource
}

note right of ExerciseRepository : Repozitář abstrahuje, odkud data pochází a jak se ukládají
note right of ExerciseViewModel
 ViewModel poskytuje stav, který se má zobrazit
 a reaguje na akce uživatele
 endnote


ExerciseRepository -- ExerciseRepositoryImpl
ExerciseListScreen -> ExerciseViewModel : Event
ExerciseListScreen <- ExerciseViewModel : State
ExerciseDetailScreen -- ExerciseViewModel
ExerciseViewModel -- ExerciseRepository
ExerciseRepositoryImpl -- RemoteExerciseDataSource
ExerciseRepositoryImpl -- LocalExerciseDataSource
LocalExerciseDataSource -- SqlDelightDataSource

ExerciseViewModel : StateFlow<Exercise>
@enduml