@startuml
'https://plantuml.com/class-diagram

package presentation {
    package ui {
        class ExerciseListScreen
        class ExerciseDetailScreen
    }
    package vm {
        class ExerciseViewModel
    }
}

package domain {
    class Exercise
}

package data {
    interface RemoteDataSource
    interface LocalDataSource
    interface Repository
}

note right of Repository : Repozitář abstrahuje, odkud data pochází a jak se ukládají
note right of ExerciseViewModel
 ViewModel poskytuje stav, který se má zobrazit
 a reaguje na akce uživatele
 endnote


ExerciseDetailScreen -- ExerciseViewModel
ExerciseListScreen -- ExerciseViewModel
ExerciseViewModel -- Repository
Repository -- RemoteDataSource
Repository -- LocalDataSource
@enduml