@startuml
'https://plantuml.com/use-case-diagram
left to right direction

actor Uživatel as User

package Systém {
    package Autentizace {
        (F01 Registrace) as (Register)
        (F02 Příhlášení) as (Login)
        (F03 Oveření emailu) as (Verify)
        (F04 Obnova zapomenutého hesla) as (Reset)
    }

    package "Interakce po přihlášení" {
        (F09 Zaznamenání tréninku) as (Record)
        (F07 Tvorba tréninkového plánu) as (Plan)
        (F14 Správa měření) as (Measure)
        (F15 Zobrazení historie záznamů) as (ShowHistory)
        (F16 Zobrazení nastavení) as (Settings)

        (F05 Výmaz uživatelského účtu) as (Delete)

        (F10 Zobrazení seznamu cviků) as (ShowExercise)
        (F11 Správa vlastního cviku) as (CustomExercise)
        (F12 Zobrazení detailu cviku) as (ShowDetail)

        (F13 Automatický časovač odpočinku) as (Timer)

        (F08 Nastavení progresivního přetížení) as (Overload)
        (F06 Odhlášení) as (Logout)
        (F18 Změna uživatelského hesla) as (ChangePassword)
    }
}

User --> (Login)
User --> (Register)
User --> (Verify)
User --> (Reset)

User --> (Record)
User --> (Plan)
User --> (ShowHistory)
User --> (Measure)
User --> (Settings)

(Record) -.> (ShowExercise) : <<include>>
(Plan) -.> (ShowExercise) : <<include>>
(ShowHistory) .-> (ShowExercise) : <<include>>

(Record) <.- (Timer) : <<extend>>

(ShowExercise) <.left. (ShowDetail) : <<extend>>
(ShowExercise) <. (CustomExercise) : <<extend>>

(Plan) <-. (Overload) : <<extend>>

(Settings) -.> (Delete) : <<include>>
(Settings) -.> (Logout) : <<include>>
(Settings) -.> (ChangePassword) : <<include>>
@enduml